frase = 'Curso em Video Python'

# FATIAMENTO DE STRINGS
print(frase[9]) # PEGA O CARACTER DA POSICAO 9
print(frase[9:14]) # VAI DO CARACTER 9 ATE O 13
print(frase[9:21:2]) # O 2 SIMBOLIZA QUE ELE VAI PULAR DE 2 EM 2
print(frase[:5]) # VAI COMECAR DO PRIMEIRO E ACABAR NO 4
print(frase[15:]) # COMECA NO 15 E VAI ATE O FINAL DA STRING'
print(frase[9::3]) # COMECA NO 9 VAI ATE O FINAL PULANDO DE 3 EM 3

# ANALISE DE STRINGS
len(frase) # DIZ QUANTOS CARACTERES TEM NA STRING
frase.count('o') # VAI CONTAR QUANTAS VEZES ESSE CARACTER APARECE
frase.count('o', 0,13) # VAI CONTAR JA COM FATIAMENTO, OU SEJA QUANTOS 0 DO CARACTER 0 AO 13
frase.find('deo') # DIZ ONDE COMECA NO CASO A POSICAO DO D
frase.find('Android') # SE NAO EXISTE NA STRING ELE RETORNA O VALOR DE -1
'Curso' in frase # OPERADOR QUE FALA SE EXISTE OU NAO NA STRING

# TRANSFORMACAO
frase.replace('Python', 'Android') # SUBSTITUI
frase.upper() # VAI DEIXAR TUDO EM MAIUSCULO
frase.lower() # VAI DEIXAR TUDO EM MINUSCULO
frase.capitalize() # DEIXA SO A PRIMEIRA MAIUSCULA
frase.title() # DEIXA A PRIMEIRA DE CADA PALAVRA EM MAIUSCULA
frase.strip() # REMOVE ESPACOS INUTEIS NO INICIO E FINAL DA STRING
frase.rstrip() # STRIP PRA DIREITA
frase.lstrip() # STRIP PRA ESQUERDA
frase.split() # DIVIDE ONDE TEM ESPACOS, AS PALAVRAS DE UMA STRING
'-'.join(frase) # VAI JUNTAR COM O SEPARADOR ESPECIFICADO NO INICIO